version: '3.9'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - database:/var/lib/docker/volumes/restproject_database/_data

  app:
    container_name: restapp
    build:
      dockerfile: Dockerfile.app
    ports:
      - 8080:8080
    links:
      - "db:database"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  proxyapp:
    container_name: proxyapp
    build:
      dockerfile: Dockerfile.proxyapp
    ports:
      - 8081:8081
    depends_on:
      - app

volumes:
  database:
    driver: local